#!/bin/bash

function cleanup {
	kill -INT $pid 2> /dev/null
	sleep 1
	kill -9 $pid 2> /dev/null
	exit
}
trap cleanup SIGHUP SIGINT SIGTERM

while true; do
	python3 ./standup.py &
	pid=$!
	inotifywait -r -e MODIFY *.py */*.py components/* views/* > /dev/null
	kill -INT $pid 2> /dev/null
	sleep 1
	kill -9 $pid 2> /dev/null
	echo; echo; echo
done
